import {
  DeviceEntity,
  DeviceBindingEntity,
  DeviceCommandEntity,
  DeviceCredentialEntity,
  DeviceStatusLogEntity,
  DeviceShadowEntity,
  DeviceRuntimeStatusEntity,
  FoodEntity,
  FoodAliasEntity,
  FoodCorrectionEntity,
  FoodLocaleNameEntity,
  FoodNutritionEntity,
  IotProvisionRecordEntity,
  IotMessageEntity,
  MealItemEntity,
  MealRecordEntity,
  RecognitionLogEntity,
  ExternalFoodMappingEntity,
} from '../common/entities/biz.entities';

export const BIZ_SERVICE_ENTITIES = [
  DeviceEntity,
  DeviceBindingEntity,
  DeviceCommandEntity,
  DeviceCredentialEntity,
  DeviceStatusLogEntity,
  DeviceShadowEntity,
  DeviceRuntimeStatusEntity,
  IotMessageEntity,
  IotProvisionRecordEntity,
  MealRecordEntity,
  MealItemEntity,
  FoodEntity,
  FoodAliasEntity,
  FoodLocaleNameEntity,
  ExternalFoodMappingEntity,
  FoodCorrectionEntity,
  FoodNutritionEntity,
  RecognitionLogEntity,
];
