  # ============================================================================
  # 依赖设施
  # ============================================================================
networks:
  lumimax:
    name: ${LUMIMAX_NETWORK:-lumimax}

services:
  postgres:
    image: registry.cn-shenzhen.aliyuncs.com/ovlb/postgres:16.13-alpine
    container_name: lumimax-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-lumimax}
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-lumimax}']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - lumimax

  redis:
    image: registry.cn-shenzhen.aliyuncs.com/ovlb/redis:7.4.8-alpine
    container_name: lumimax-redis
    restart: unless-stopped
    expose:
      - '6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - lumimax

  rabbitmq:
    image: registry.cn-shenzhen.aliyuncs.com/ovlb/rabbitmq-delayed:3.13.3-management
    container_name: lumimax-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-root}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-root}
    expose:
      - '5672'
      - '15672'
    # ports:
    #   - '${RABBITMQ_MANAGEMENT_PORT:-15672}:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - lumimax

  emqx:
    image: registry.cn-shenzhen.aliyuncs.com/ovlb/emqx.emqx:5.8.6
    container_name: lumimax-emqx
    restart: unless-stopped
    environment:
      EMQX_AUTHENTICATION__1__HEADERS__AUTHORIZATION: Bearer ${EMQX_AUTH_SECRET:-replace-with-long-random-token}
      EMQX_AUTHORIZATION__SOURCES__1__HEADERS__AUTHORIZATION: Bearer ${EMQX_AUTH_SECRET:-replace-with-long-random-token}
    expose:
      - '1883'
      - '8883'
      - '8083'
      - '8084'
      - '18083'
      - '18084'
    ports:
      - '${EMQX_MQTT_PORT:-2883}:1883'
      - '${EMQX_MQTTS_PORT:-8883}:8883'
      - '${EMQX_DASHBOARD_PORT:-28083}:18083'
      - '${EMQX_DASHBOARD_TLS_PORT:-28084}:18084'
    volumes:
      - ../docker/emqx/base.hocon:/opt/emqx/etc/base.hocon:ro
      - ../docker/emqx/certs:/opt/emqx/etc/certs:ro
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
    healthcheck:
      test: ['CMD', '/opt/emqx/bin/emqx_ctl', 'status']
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - lumimax

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:
  emqx-data:
  emqx-log:
